#!/bin/bash
shopt -qs nullglob

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 'ERROR: Cannot determine script directory!'; exit 3; }
readonly scriptName="$(basename -- "${BASH_SOURCE[0]}")"

runHook()
{
    local hookFilespec="${1:?}"; shift
    [ -x "$hookFilespec" ] || return 0
    "$hookFilespec" "$@"; local status=$?
    return $((status == 99 ? 0 : status))   # Special status: Skip the global hook(s).
}

# The global hook runs within the working copy where the commit is made and can
# therefore check if a local hook exists in it's .git directory.
gitDir=$(git rev-parse --git-dir 2>/dev/null) || exit 3
for hook in "${gitDir}/hooks/${scriptName}" "${scriptDir}/${scriptName}.d"/*; do
    runHook "$hook" "$@" || exit $?
done
