#!/bin/sh

if [ $# -eq 0 ]; then
    echo >&2 'ERROR: No <branch> passed.'
    exit 2
elif [ $# -gt 1 ]; then
    echo >&2 'ERROR: Must pass only one <branch>.'
    exit 2
fi

# First check whether any valid ref is passed.
git rev-parse --verify --quiet "$@" >/dev/null || exit 1

# Then verify that a branch with that name exists (and it isn't a tag or raw
# commit).
[ "$(git branch --list --all "$@")" ]
