#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Print / execute GIT-COMMAND with the revision range that comprises the current
branch / N previous branches; possibly including one previous commit (from which
was branched off).
The revision range (with --no-range, only the starting revision will be used) is
appended at the end of GIT-COMMAND ...; with --keep-last, it is put between the
next-to-last and last arguments.
A different GIT-COMMAND2 can be used for the --one-more revision; with ^[1|2],
the modifier instead is appended to the revision, and there's only one
invocation of GIT-COMMAND.
HELPTEXT
printf 'Usage: %q %s\n' "$(basename "$1")" '[-n|--branch-number N] [--no-range] [--start-rev REV] [-a|--any|-r|--include-remote-refs|-t|--include-tags [...]] [--keep-last] [+1|--one-more|--one-more-command GIT-COMMAND2|^[1|2]] [GIT-COMMAND ...] [-?|-h|--help]'
}

let branchNumber=1
isAny=
startRev=
typeset -a include=('heads')
typeset -a revRangeArgs=()
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)			shift; printUsage "$0"; exit 0;;
	--branch-number|-n)		shift; branchNumber="$1"; shift;;
	--start-rev)			shift; startRev="$1"; shift;;
	--any|-a)			shift; isAny=t;;
	--include-remote-refs|-r)	shift; include+=('remotes');;
	--include-tags|-t)		shift; include+=('tags');;
	*)				revRangeArgs+=("$1"); shift;;
    esac
done

contains()
{
    needle=$1
    shift
    for elem
    do
	[ "$needle" = "$elem" ] && return 0
    done
    return 1
}

previousRev="${startRev:-HEAD}"
let branchCnt=0
while [ $branchCnt -lt $branchNumber ]
do
    while :
    do
	# This will exit eventually with
	#	"fatal: Not a valid object name REV^" or
	#	"fatal: No tags can describe REV".
	previousRev=$(git describe --abbrev=0 --all "${previousRev}^") || exit $?
	[ "$isAny" ] && break
	contains "${previousRev%%/*}" "${include[@]}" && break
    done
    let branchCnt+=1
done

exec git-rev-range --revision "$previousRev" ${startRev:+--end-revision} $startRev "${revRangeArgs[@]}"
