#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Pickaxe: Show log (and commits with -p) where text or /regexp/ was changed.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[<options>] [<since>..<until>] [[--] <path>...] text|/regexp/ [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
lastArg=${!#}
case "$lastArg" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

if [ $# -eq 0 ]; then
    printUsage "$0"
    exit 2
fi

# The last argument is the text or /regexp/.
if [ "$lastArg" = '-p' -o "$lastArg" = '--pretty=oneline' ]; then
    # Check for no arguments given to findchange and findlg aliases.
    printUsage "$0"
    exit 2
fi

searchString=$(printf '%s' "$lastArg" | sed -ne 's/^\([^a-zA-Z0-9]\)\(.*\)\1$/\2/p')
[ "$searchString" ] && allargs+=("--pickaxe-regex") || searchString=$lastArg

exec git log "${@:1:$(($#-1))}" "-S$searchString"
