#!/bin/bash

case $# in
    0)	[ -n "$(git remote show 2>/dev/null)" ];;
    1)	git config "remote.${1:?}.url" >/dev/null;;
    *)	echo >&2 "ERROR: Pass one <remote> or nothing to check whether any remote is defined."; exit 2;;
esac
