#!/bin/bash

lastBranch="$(git rev-parse --symbolic-full-name '@{-1}')" || exit $?
if [ -z "$lastBranch" ]; then
    echo >&2 'ERROR: Cannot resolve last checked-out branch name.'
    exit 1
fi

lastBranch="${lastBranch#refs/heads/}"
exec git-reintegrateto --branch "$lastBranch" "$@"
