#!/bin/bash

if [ $# -lt 2 ]; then
    echo >&2 'ERROR: Need to pass GIT-COMMAND and SOURCE-COMMAND'
    exit 2
fi

gitCommand="$1"; shift
sourceCommand="$1"; shift

typeset -a files=($(git-wrapper "$sourceCommand"))
[ ${#files[@]} -eq 0 ] && exit 1

exec git-wrapper "$gitCommand" "$@" -- "${files[@]}"
