#!/bin/bash
# Source:
#   http://codingkilledthecat.wordpress.com/2012/04/27/git-stash-pop-considered-harmful/

printUsage()
{
    cat <<HELPTEXT
Stash the changes in a dirty working directory in a new branch.
HELPTEXT
    printf 'Usage: %q  %s\n' "$(basename "$1")" '<branch> [-m <msg>] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -eq 0 ]; then
    echo >&2 'Need new <branch> to stash to!'
    exit 2
fi

newBranch=$1; shift
git checkout -b "$newBranch" && git commit --all "$@" && git checkout '@{-1}'
