#!/bin/bash
set -e

printUsage()
{
    cat <<HELPTEXT
Test whether the current working copy directly refers to a particular commit as
opposed to a named branch.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

# Logic taken from __git_ps1 (in /usr/lib/git-core/git-sh-prompt).
gitDir="$(git rev-parse --git-dir 2>/dev/null)"
read -r head < "${gitDir}/HEAD"
[ "${head#ref: }" = "$head" ]
