#!/bin/bash
set -o pipefail

if  [ "$1" = '--no-range' ]; then
    shift
    rangeArg="$(git lh --since yesterday | tail -n 1)" || exit $?
else
    # For commands that take a range (i.e. the log variants), we can directly
    # inject the --since argument.
    rangeArg="--since yesterday"
fi

exec git-wrapper "$1" $rangeArg "${@:2}"
