#!/bin/sh
# Source: http://www.aaronwest.net/blog/index.cfm/2011/6/7/Git-Workflows-Archiving-Old-Branches

if [ $# -eq 0 ]; then
    echo >&2 'Need <branch> to archive!'
    exit 2
fi

branchDeleteOption=-d
tagForceOption=
case $1 in
    -f|--force)	shift; branchDeleteOption=-D; tagForceOption=-f;;
esac

status=0
for branch
do
    git tag $tagForceOption "archive/$branch" "$branch" || status=1
done
[ $status -eq 0 ] || exit $status

git push --tags origin || exit $?

status=0
for branch
do
    git branch $branchDeleteOption "$branch" || status=1
done
for branch
do
    git push origin --delete "$branch" || status=1
done
exit $status
