#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Diff with predecessor, either current HEAD or passed commit,
optionally limited to files in <path>.
Like the textual diff output of "git show", without the log info.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[<commit>] [<common diff options>] [--] [<path>...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

revision='HEAD'
if [ $# -gt 0 -a "${1:0:1}" != '-' -a ! -e "$1" ]; then
    # Take the first argument as a commit specification unless it looks like a
    # diff argument or is an existing file.
    revision=$1
    shift
fi

exec git ${GIT_DP_DIFFCOMMAND:-diff} "${revision}^" "$revision" "$@"
