#!/bin/bash

ensureValidRef()
{
    if ! git-existsbr "$1"; then
	printf >&2 'ERROR: Branch %s does not exist!\n' "$1"
	exit 1
    fi
}

if [ $# -eq 2 ]; then
    localBranch=$1
    remoteBranch=$2
elif [ $# -eq 1 ]; then
    localBranch=$(git-brname)
    case "$1" in
	*/*)	remoteBranch=$1;;
	*)	remoteBranch=$(git-remotebr "$1") || exit $?;;
    esac
else
    localBranch=$(git-brname)
    remoteBranch=$(git tracks) || exit $?
fi

ensureValidRef "$localBranch"
ensureValidRef "$remoteBranch"

set -o pipefail
(
    echo "incoming ${remoteBranch} -> ${localBranch}:"
    git-onelinelog --no-pager "$localBranch..$remoteBranch"

    echo
    echo "outgoing ${localBranch} -> ${remoteBranch}:"
    git-onelinelog --no-pager "$remoteBranch..$localBranch"
) | "${PAGER:-less}" --RAW-CONTROL-CHARS
