#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Interactively select (from staged files or passed list of files) files (or
directly pass N, M, ... selections) to remove from the index by number.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[N [M ...]] [--] [FILE ...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

export GIT_SELECTED_COMMAND_DEFAULT_FILES='git diff --name-only --cached'
exec git-selected-command unstage "$@"
