#!/bin/bash

remote="${1:?}"; shift
url=$(git-remoteurl "$remote") || exit $?
branch=$(git-brname | urlencode --filespec -) || exit $?

exec git-lll --prefix "${url%/}/blob/${branch}/" --transform 'urlencode --filespec --newlines -' "$@"
