#!/bin/bash

readonly FORMAT='%C(cyan)%h%Creset %Cgreen(%aN, %ar)%Creset %C(red bold)%d%Creset %s'
gitDirectArg="$1"; shift
git $gitDirectArg log --abbrev-commit --date=relative --decorate --pretty="tformat:${FORMAT//${GIT_ONELINELOG_NOFORMAT:-}/}" "$@"
