#!/bin/sh
# Source: https://github.com/sschuberth/dev-scripts/blob/master/git/git-rename-remote-branch.sh

printUsage()
{
    cat <<HELPTEXT
Rename a branch on the server without checking it out.
Usage: "$(basename "$1")" <remote> <old> <new>
Example: "$(basename "$1")" origin master release
HELPTEXT
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -ne 3 ]; then
    printUsage "$0"
    exit 2
fi

git push $1 ${1}/${2}:refs/heads/${3} :$2
