#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Interactively select (from files touched in <commit>) files (or directly pass N,
M, ... selections) to be reverted to what the content *before* <commit> was.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '<commit> [N [M ...]] [--] [FILE ...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

if git-dirty; then
    echo >&2 "ERROR: working copy is still dirty; please clean up first."
    git status
    exit 1
fi

export GIT_CHECKOUTPREVIOUS_COMMIT="${1:?}"; shift
export GIT_SELECTED_COMMAND_DEFAULT_FILES="git-showfiles $GIT_CHECKOUTPREVIOUS_COMMIT --"
exec git-selected-command checkoutprevious "$@"
