#!/bin/bash

# Need to specify a branch, because the current branch presumably tracks origin,
# not upstream. Because of this, Git wouldn't normally allow pulling from
# upstream:
# > You asked to pull from the remote 'upstream', but did not specify
# > a branch. Because this is not the default configured remote
# > for your current branch, you must specify a branch on the command line.
typeset -a args; args=($(git-parse-last-remotebr-argument --separate-remote-and-branch upstream "$@")) || exit $?
set -- "${args[@]}"

git-up "$@" || exit $?

path=${!#}
if git-existsremote origin; then
    git push origin "$path"
fi
