#!/bin/bash
set -o pipefail

typeset -a dates=("$(date "+%F 03:00" 2>/dev/null || printf yesterday)" '7 days ago' '30 days ago' '365 days ago' '')

typeset -a gitCommand=()
case "$1" in
    [^-]*-command)  gitCommand+=("$1"); shift
		    while [ $# -ne 0 ]
		    do
			case "$1" in
			    --)		break;;
			    -*)		gitCommand+=("$1"); shift;;
			    *)		gitCommand+=("$1"); shift; break;;
			esac
		    done
		    ;;
    *)		    while [ $# -ne 0 ]
		    do
			case "$1" in
			    -c) gitCommand+=("$1" "$2"); shift; shift;;
			    *)	gitCommand+=("$1"); shift; break;;
			esac
		    done
esac

previousDate=
for date in "${dates[@]}"
do
    typeset -a rangeArgs=()
    [ "$date" ] && rangeArgs+=("--since=$date")
    [ "$previousDate" ] && rangeArgs+=("--until=$previousDate")
    previousDate="$date"

    git-wrapper "${gitCommand[@]}" "${rangeArgs[@]}" "$@"
done
