#!/bin/bash

remote="${1:?}"; shift

url=$(git-remoteurl "$remote")
escapedUrl=${url//\\/\\\\}
escapedUrl=${escapedUrl//#/\\#}
escapedUrl=${escapedUrl//&\\&}

git log --pretty=tformat:%H "$@" | sed -e "s#^#${escapedUrl}/commit/#"
