#!/bin/bash

if [ -z "$GIT_BASE_BRANCH" ]; then
    echo >&2 'ERROR: GIT_BASE_BRANCH not defined!'
    exit 2
fi

git reset --hard --quiet "$@" && git-base-command checkout --quiet && git-base-command uwipe
