#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
List all git command extensions and newly defined commands. 
Usage: "$(basename "$1")" [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

sed \
    -e '
	/^\[alias\]/,/^\[/{
	    /^\[/d;
	    /^[ \t]*;/d;
	    s/^[ \t]*//g;
	    s/[ \t];[ \t]*/\n\t/;
	    b
	}' \
    -e 'd' \
    ~/.gitconfig \
    | sed -e '/^\t/!s/.*/[01m&[0m/'
