#!/bin/sh

git clone "$@" || exit 1
eval repoOrDir=\$$#
cloneDir=${repoOrDir%.git}
cloneDir=${cloneDir##*/}
[ -d "$cloneDir" ] || { echo >&2 "Cannot locate working copy; quitting"; exit 1; }

if [ "$(uname -o 2>/dev/null)" = "Cygwin" ]; then
    echo 'Applying tailorings for Cygwin:'
    cd "$cloneDir" || exit 1
    git config core.filemode false
    git config http.sslVerify false
fi
