#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Look up person by name or email address, based on all previous committers to the
repository. With --accept-unknown, will also accept new names in the form
NAME EMAIL@HOST (two arguments) or "NAME <EMAIL@HOST>" (one argument) that are
not yet found in the repository.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-1|--first|-s|--select] [--accept-unknown] AUTHOR-PATTERN|NAME EMAIL@HOST|"NAME <EMAIL@HOST>" [-?|-h|--help]'
}
isAcceptUnknown=
isShowFirstCandidate=
isSelect=
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--accept-unknown)   shift; isAcceptUnknown=t;;
	--first|-1)	shift; isShowFirstCandidate=t;;
	--select|-s)    shift; isSelect=t;;
	--)		shift; break;;
	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
	*)		break;;
    esac
done


selectCandidates()
{
    if [ $# -eq 0 ]; then
	echo >&2 'ERROR: No candidates found.'
	exit 1
    elif [ $# -eq 1 ]; then
	printf '%s\n' "$1"
    else
	select person
	do
	    if [ "$person" ]; then
		printf '%s\n' "$person"
		exit 0
	    elif [ ! "$REPLY" ]; then
		exit 1
	    elif [ "$REPLY" = '?' ]; then
		cat >&2 <<-'EOF'
		    Enter a number to select the person.
		    Filter the list by entering "grep" arguments. (Double backslashes.)
		    Abort via Ctrl-D.
EOF
	    else
		typeset -a filteredCandidates=($(printf '%s\n' "$@" | grep $REPLY))
		selectCandidates "${filteredCandidates[@]}"
		break
	    fi
	done
    fi
}

IFS=$'\n'
typeset -a candidates=($(git log -i ${isShowFirstCandidate:+-1} --pretty='tformat:%aN <%aE>' ${1:+--author="$1"} | sort --unique))

if [ ${#candidates[@]} -eq 0 ]; then
    if [ "$isAcceptUnknown" -a \( $# -eq 1 -o $# -eq 2 \) ]; then
	case $# in
	    1)	person="$1";;
	    2)	person="$1 <$2>";;
	esac
	if [[ "$person" =~ ^[^\ ].*[^\ ]\ \<[^\ ]+@[^\ ]+\>$ ]]; then
	    printf '%s\n' "$person"
	    exit
	else
	    echo >&2 "ERROR: Did not pass a valid NAME <EMAIL@HOST>!"
	    exit 2
	fi
    fi

    exit 1
fi

if [ "$isShowFirstCandidate" ]; then
    printf '%s\n' "${candidates[0]}"
elif [ "$isSelect" ]; then
    selectCandidates "${candidates[@]}"
else
    printf '%s\n' "${candidates[@]}"
fi
