#!/bin/bash

previousRev=$(git describe --abbrev=0 --all HEAD^) || exit $?

isKeepLastArgument=
while [ $# -ne 0 ]
do
    case "$1" in
	--keep-last)	shift; isKeepLastArgument=t;;
	*)		break;;
    esac
done

if [ $# -gt 0 -a "$isKeepLastArgument" ]; then
    exec git "${@:1:$(($#-1))}" "${previousRev}^.." "${!#}"
else
    exec git "$@" "${previousRev}^.."
fi
