#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show all commits from today unless a different date or commit range is given.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--since=<date>] [<path>] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ -t 1 ] && colorArg="--color" || colorArg="--no-color"

sinceArg='--since="03:00"'
for argument
do
    case "$argument" in
	--since=*)  sinceArg=;;
	*..*)	    sinceArg=;;
    esac
done

if [ "$GIT_LOGTODAY_LOG_COMMAND" ]; then
    eval "$GIT_LOGTODAY_LOG_COMMAND $colorArg $sinceArg" '"$@"'
else
    readonly gitUserName=$(git config --get user.name)
    eval 'git-log $colorArg --pretty=medium' $sinceArg '"$@"' | sed -e "
    /Author: ${gitUserName}/d"'
    /^Date:/d
    /^Merge:/d' | "${PAGER:-less}" --RAW-CONTROL-CHARS
fi
