#!/bin/sh
set -o noglob

# Need to specify a branch, because the current branch presumably tracks origin,
# not upstream. Because of this, Git wouldn't normally allow pushing to
# upstream:
# > fatal: You are pushing to remote 'upstream', which is not the upstream of
# > your current branch 'master', without telling me what to push to update
# > which remote branch.
set -- $(git-parse-last-remotebr-argument --separate-remote-and-branch upstream "$@")
exec git push "$@"
