#!/bin/bash

if [ -z "$GIT_BASE_BRANCH" ]; then
    echo >&2 'ERROR: GIT_BASE_BRANCH not defined!'
    exit 2
elif [ $# -eq 0 ]; then
    echo >&2 'ERROR: No GIT-COMMAND passed.'
    exit 2
fi

typeset -a baseArgs=()
case "$1" in
    -[1-9])
	typeset baseArgNum=${1#-}
	baseArgs=("${@:2:${baseArgNum}}")
	set -- "${@:$((2 + baseArgNum))}"

	baseArgs=("${baseArgs[@]//BASE/${GIT_BASE_BRANCH}}")

	exec git-wrapper "$@" "${baseArgs[@]}"
	;;
    --keep-position)
	shift
	exec git-wrapper "${@//BASE/${GIT_BASE_BRANCH}}"
	;;
    *)
	exec git-wrapper "$@" "$GIT_BASE_BRANCH"
	;;
esac
