#!/bin/bash

hasStashed=
if git-dirty; then
    git-stashi || exit $?
    hasStashed=t
fi
git-adduntracked && git-commit "$@"
status=$?
if [ "$hasStashed" ]; then
    git stash pop || exit $?
fi
exit $status
