#!/bin/bash

if [ $# -eq 0 ]; then
    typeset -a dirtyArg=(--dirty)
else
    typeset -a dirtyArg=()
fi

git describe --tags "${dirtyArg[@]}" "$@" 2>/dev/null ||
    git describe --always --all "${dirtyArg[@]}" "$@"
