#!/bin/bash

remote=$(git remote get-url -- "$@") || exit $?
case "$remote" in
    *://*)  printf '%s\n' "$remote"; exit;;
esac

url=$remote
url="${url#git@}"
url="${url%.git}"
url="https://${url/:/\/}"
printf '%s\n' "$url"
