#!/bin/bash

IFS=$'\n'
for filespec in $(find "$@" -mindepth 1 -maxdepth 1 -type f -print | sort)
do
    file=${filespec#./}
    git log --pretty=format:"${file//%/%%}" --max-count 2 -- "$filespec"
done
