#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Enter a bunch of git commands interactively. 
Usage: "$(basename "$1")" [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

while read -p "git> " line; do
    if [ "x$line" != "xexit" ]; then
	git $line;
    else
	echo "bye";
	break;
    fi;
done
