#!/bin/bash
# Source: https://stackoverflow.com/a/25109122/813602

if [ $# -gt 0 ]; then
    case "$1" in
	*/*)	remoteBranch=$1;;
	*)	remoteBranch="${1}/$(git-brname)";;
    esac
    if ! git-existsbr "$remoteBranch"; then
	printf >&2 'ERROR: remote branch %s does not exist!\n' "$remoteBranch"
	exit 1
    fi
else
    remoteBranch=$(git-tracks) || exit $?
fi

set -o pipefail
remoteRev="$(git ls-remote "${remoteBranch%%/*}" "${remoteBranch#*/}" | cut -f1)" || exit 1
localRev="$(git rev-parse HEAD)"
if [ "$localRev" = "$remoteRev" ]; then
    printf '%s\n' "up to date"
else
    printf '%s\n' "not up to date"
fi
