#!/bin/sh

what="refs/heads/$1"
case $1 in
    -a)	what="refs/heads/$2 refs/remotes/$2";;
    -r) what="refs/remotes/$2";;
esac
git for-each-ref --sort=committerdate --format='(%(authorname), %(committerdate:relative))%09%(refname:short)' $what
