#!/bin/sh

branch=$(git symbolic-ref HEAD) || exit $?
branch=${branch##refs/heads/}

force=
case $1 in
    --force|-f)	force=$1; shift;;
esac
ubranch=${1:-master}
if [ "$ubranch" = 'master' -a "$branch" != 'master' ]; then
    # Typically, one does not reset one's branch to upstream's master.
    printf %s "Really reset branch \"${branch}\" to upstream/${ubranch}? (y/n) "
    read answer
    [ "$answer" = "y" ] || exit 1
fi

git-hardreset $force "$@" "upstream/$ubranch"
