#!/bin/bash
set -o pipefail

# Highlight diff output if available.
hasColorDiff=
type -t colordiff >/dev/null && [ -t 1 ] && hasColorDiff=t

isAsDiffTool=
typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--as-difftool) shift; isAsDiffTool=t;;
	--no-color|--color=never)
	    shift
	    hasColorDiff=
	    ;;
	--color|--color=always)
	    shift
	    hasColorDiff=t
	    ;;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done
set -- "${allargs[@]}"

if [ "$isAsDiffTool" ]; then
    if [ $# -eq 0 ]; then
	echo >&2 'ERROR: No FILEs passed.'
	exit 2
    fi

    ${hasColorDiff:+color}diff -c "$@"
    exit 0	# Need to return success to avoid that Git complains that the "external tool died".
else
    colorArg=--color=always; [ "$hasColorDiff" ] || colorArg=--no-color

    git difftool --no-prompt --extcmd="git-diffc --as-difftool $colorArg" "$@" | "${PAGER:-less}" --quit-on-intr --RAW-CONTROL-CHARS
fi
