#!/bin/bash
shopt -qs extglob

gitCommand=${1:?}; shift
exec commandOnSelected \
    --generator "${GIT_SELECTED_COMMAND_DEFAULT_FILES:-git ls-files --modified --}" \
    --command "git-wrapper $gitCommand" \
    -- "$@"
