#!/bin/sh

lastArg=; [ $# -gt 0 ] && lastArg=${!#}
path="origin/$lastArg"
if git-existsbr "$path"; then
    set -- "${@:1:$(($#-1))}"
elif ! path="$(git-remotebr origin)"; then
    printf >&2 'ERROR: Cannot find corresponding origin branch; origin/%s does not exist.\n' "$(git-brname)"
    exit 1
fi

git reset "$@" "$path"
