#!/bin/sh
## Remove unversioned files. 
## with -r also any unversioned directory trees. 
## with -x also files from the ignore list. 

recursiveFlag=
if [ "$1" = "-r" ]; then
    recursiveFlag='-d'
    shift
fi

git clean $recursiveFlag "$@"
