#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Pickaxe: Log where text or /regexp/ was added or removed (i.e. those filepairs
whose preimage and postimage have different number of occurrences of the text).
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[<log-options>] [<since>..<until>] [[--] <path>...] text|/regexp/ [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
lastArg=${!#}
case "$lastArg" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

if [ $# -eq 0 ]; then
    printUsage "$0"
    exit 2
fi

# The last argument is the text or /regexp/.
case "$lastArg" in
    # Check for no arguments given to findchanges, findlogsv and findlg aliases.
    -p|--pretty=oneline|--name-status|--date=relative)
	printUsage "$0"
	exit 2
	;;
esac

searchString=$(printf '%s' "$lastArg" | sed -ne 's/^\([^a-zA-Z0-9]\)\(.*\)\1$/\2/p')
[ "$searchString" ] && set -- --pickaxe-regex "$@" || searchString=$lastArg

exec git-wrapper "${GIT_PICKAXE_COMMAND:-log}" "${@:1:$(($#-1))}" "-S$searchString"
