#!/bin/sh

if [ $# -eq 0 ]; then
    echo >&2 'Need <branch> to merge to!'
    exit 2
fi
targetBranch=$1
shift

branch=$(git symbolic-ref HEAD) || exit $?
branch=${branch##refs/heads/}

git checkout "$targetBranch" && git merge "$@" "$branch"
