#!/bin/sh

branch=$(git symbolic-ref HEAD) || exit $?
branch=${branch##refs/heads/}
remote=$(git config "branch.${branch}.remote") || exit $?
remoteBranch=$(git config "branch.${branch}.merge") || exit $?
remoteBranch=${remoteBranch##refs/heads/}

echo "${remote:?}/${remoteBranch:?}"
