#!/bin/bash

me="$(git config --get user.name)" || exit $?

optionName='--author='
if [ "$1" = '--no-option-name' ]; then
    shift; optionName=
fi

exec git-wrapper "$1" "${optionName}${me}" "${@:2}"
