#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Create (and track) local branches for all branches in origin (matching <pattern>).
Usage: "$(basename "$1")" [-q|--quiet] [<pattern>] [-?|-h|--help]
HELPTEXT
}

option=
case "$1" in
    -*)	option=$1; shift;;
esac

exec git-cobr $option origin "$@"
