#!/bin/bash
set -o pipefail

yesterdayTimestamp='yesterday'

typeset -a rangeArgs=()
if  [ "$1" = '--no-range' ]; then
    shift
    rangeArgs=("$(git lh --since "$yesterdayTimestamp" | tail -n 1)") || exit $?
else
    # For commands that take a range (i.e. the log variants), we can directly
    # inject the --since argument.
    rangeArgs=('--since' "$yesterdayTimestamp")
fi

exec git-wrapper "$1" "${rangeArgs[@]}" "${@:2}"
