#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Enter a bunch of git commands interactively.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-?|-h|--help]'
}

isWrapped=
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --wrapped)		shift; isWrapped=t;;
esac
if [ ! "$isWrapped" ] && type -t rlwrap >/dev/null; then
    readonly scriptFilespec="${BASH_SOURCE[0]}"
    exec rlwrap "$scriptFilespec" --wrapped "$@"
fi

while read -p "git> " line; do
    if [ "$line" = exit ]; then
	echo "bye"
	break
    fi
    git $line
done
