#!/bin/sh
# Unfortunately, git blame can only omit both author and timestamp via -s. 
# I just want to get rid of the timestamp. 
# -M detects moving lines in the file. 
git blame -M -t "$@" | sed -e 's/^\([^(]*\)(\([^)]*\) [0-9]\+ [+-][0-9]\+ \+[0-9]\+)/\1 \2)/'
