#!/bin/sh

# XXX: The man page for -x says "This is done only for cherry picks without
# conflicts.", but I found this not to be true (git version 2.7.4). Actually, I
# wanted to implement a work-around for that, because I want a reference to the
# original commit also for conflicted merges.
exec git cherry-pick -x "$@"
