#!/bin/bash

readonly scriptDir=$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 2)
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 2; }

# Render primitive subset of Markdown.
sed -e 's/^# \(.*\)$/[01;36m\1[0m/' \
    -e 's/^## \(.*\)$/[01;35m\1[0m/' \
    -e 's/^#\{3,\} \(.*\)$/[01m\1[0m/' \
    -e 's/^    .*/[47m&[0m/' \
    -e 's/`\([^`]\+\)`/[47m\1[0m/g' \
    -e 's/\(^\| \)\*\*\([^ ].*[^ ]\)\*\*\( \|$\)/[01m\2[0m/g' \
    "${scriptDir}/gitcheats${1:+"-$1"}.md" | \
    "${PAGER:-less}" --RAW-CONTROL-CHARS
