#!/bin/bash
set -o pipefail

if [ $# -eq 0 ]; then
    echo >&2 "ERROR: Must pass remote and branch name"
    exit 2
fi
remote=$1; shift

git branch -r --list "${remote}/${1:-*}" | sed -e "/^ *${remote}\/HEAD -> /d"
