#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Commit with the intent of squashing this with the passed <commit> (id or
:/<pattern>) via interactive rebase later.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '<ref>|:/<pattern> [<commit-arguments> ...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -eq 0 ]; then
    printUsage "$0" >&2
    exit 2
fi

fixupCommit=$1; shift

# --fixup will do good error handling for us ("fatal: could not lookup commit
# :/doesNotExist), just pass it along.
exec git-commit --fixup "$fixupCommit" "$@"
