#!/bin/bash

if [ $# -eq 0 ]; then
    typeset -a dirtyArg=(--dirty)
else
    typeset -a dirtyArg=()
fi

git describe --tags "${dirtyArg[@]}" "$@" 2>/dev/null && exit
description="$(git describe --always --all "${dirtyArg[@]}" "$@")" || exit $?
[ "$description" ] || exit 1
printf '%s\n' "${description#heads/}"
