#!/bin/bash

git symbolic-ref --short --quiet HEAD 2>/dev/null && return

# Git 1.7.9 on Cygwin doesn't understand the --short option; fall back to
# shorting it ourselves.
longOrig=$(git symbolic-ref --quiet HEAD 2>/dev/null)
printf '%s\n' "${longOrig#refs/heads/}"
