#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
List unversioned files, show a summary for unversioned directories
or with -l the entire subdir contents. 
Usage: "$(basename "$1")" [-l] [<path>] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

isLongFormat=
if [ "$1" = "-l" ]; then
    isLongFormat='true'
    shift
fi

git clean --dry-run -d "$@" | sed -e 's/^Would \(not \)\?remove //' | while read filespec
do
    if [ -d "$filespec" ]; then
	if [ "$isLongFormat" ]; then
	    find "$filespec"
	else
	    fileNum=$(find "$filespec" -type f | wc -l)
	    dirsize=$(du -s --human-readable -- "$filespec" | cut -f 1)
	    echo "$filespec [directory; $fileNum file$([ $fileNum -eq 1 ] || printf 's'), ${dirsize}]"
	fi
    else
	echo "$filespec"
    fi
done
