#!/bin/bash
set -o pipefail
shopt -qs extglob

if [ $# -eq 0 -o $# -gt 2 ]; then
    echo >&2 "ERROR: Must pass remote and optionally branch pattern"
    exit 2
fi
remote=$1
branchPattern=$2

currentBranch="$(git-remotebr "$remote" 2>/dev/null || echo "(remote branch not found)")"
remoteBranch="$(git-brc -r "${remote}/${branchPattern}" | awk '{ print $NF }' | grep -v -F --line-regexp -e "${remote}/master" ${GIT_BASE_BRANCH:+-e "${remote}/$GIT_BASE_BRANCH"} -e "$currentBranch" | tail -n 1)" || exit $?
if [ -z "$remoteBranch" ]; then
    # git branch does not return an error if there are no matches for the passed pattern.
    printf >&2 'ERROR: No branch matching %s/%s (excluding the current %s and master%s) found.\n' "$remote" "$branchPattern" "$currentBranch" "${GIT_BASE_BRANCH:+ and ${GIT_BASE_BRANCH}}"
    exit 1
fi
exec git checkout --track "${remoteBranch##+( )}"
