#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Interactively select (from modified files or passed list of files) files (or
directly pass N, M, ... selections) to stage by number.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[N [M ...]] [--] [FILE ...] [-?|-h|--help]'
}

addCommand='add'
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --edit|--patch)	addCommand="$addCommand $1"; shift;;
esac

exec git-selected-command "$addCommand" "$@"
