#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Execute "git COMMAND" on each passed WORKING-COPY.
Puts a header line (unless --no-header) that contains the WORKING-COPY name
(with --branch-name: also the current Git branch) before COMMAND's output.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--no-pager] [--no-header|--branch-name] WORKING-COPY [...] -- [COMMAND ...] [-?|-h|--help]'
}

typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
isHeader=t
isBranchName=
emptyHeaderFilterCommand=filterEmptyHeaders
typeset -a wcs=()
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--no-pager)	shift; pager=();;
	--no-header)	shift; isHeader=; emptyHeaderFilterCommand=cat;;
	--branch-name)	shift; isBranchName=t;;
	--)		shift; break;;
	*)		wcs+=("$1")
			shift
			;;
    esac
done
[ ${#wcs[@]} -eq 0 ] && { printUsage "$0" >&2; exit 2; }
[ $# -eq 0 ] && set -- noop

# Because of the piping into the pager, we need to explicitly enable color.
# Don't do this if the user explicitly turned it off, though.
typeset -a colorArg=(--color=always)
if [ ! "$pager" -o ! -t 1 ] || contains '--no-color' "$@" || contains '--color=never' "$@"; then
    colorArg=()
fi



filterEmptyHeaders()
{
    awk '
	/^\[01m.+\[0m:$/ {
	    suspect = $0
	    while (1) {
		lookahead = ""
		while (lookahead ~ /^\n*$/) {
		    if (getline lookahead != 1) {
			next
		    }
		}
		if (lookahead ~ /\n*\[01m.+\[0m:$/) {
		    gsub(/^\n*/, "", lookahead)
		    suspect = lookahead
		} else {
		    print suspect
		    print lookahead
		    fflush()
		    next
		}
	    }
	}
	{
	    print
	    fflush()
	}
    ' | sed --unbuffered -e '${ /^$/d }'
}

separator=
exitStatus=0
for dir in "${wcs[@]}"
do
    cd "$dir" || { exitStatus=$?; continue; }

    if [ "$isHeader" ]; then
	header="${dir##*/}"
	[ "$isBranchName" ] && header="${header%.*} on $(git-brname || echo 'unknown branch')"
	printf "${separator}[01m%s[0m:\n" "$header"
    fi

    git "$@" "${colorArg[@]}" || exitStatus=$?

    separator='\n'
done 2>&1 | eval "filterEmptyHeaders ${pager:+|}" '"${pager[@]}"'
exit $exitStatus
