#!/bin/bash

fileBlame()
{
    git ls-files "$@" | xargs -n 1 -I {} git log -1 --pretty=tformat:'%h %aN (%ar)	{}' -- {} | column -s $'\t' -t
}

typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
eval 'fileBlame "$@"' "${pager:+|}" '"${pager[@]}"'
