#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show statistics on how many lines were last committed by which author.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '--since=<date> [<commit>] <file> [-?|-h|--help]'
}

case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

git-shortblame "$@" | cut -d' ' -f 3 | sort | uniq -c | sort -r
