#!/bin/bash
# Source: http://www.commandlinefu.com/commands/view/10601/open-the-current-project-on-github-by-typing-gh

if type -P browse > /dev/null; then
    browser=browse
else
    browser=open
fi
git remote -v | grep fetch | grep "${1:-origin}" | sed 's/\(.*github.com\)[:|/]\(.*\).git (fetch)/\2/' | awk {'print "https://github.com/" $1'} | xargs "$browser"
