#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Undo the automatic "Reuse recorded resolution" by overriding the working tree
with the version with conflict markers.
Supply <paths> or use -a to apply this to all conflicted files in the index.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-a|--all] [--] [<file>...] [-?|-h|--help]'
}
typeset -a allFiles
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --all|-a)		shift
			IFS=$'\n'
			allFiles=($(git conflicts))
			[ ${#allFiles[@]} -gt 0 ] || { echo >&2 "No conflicts found!"; exit 1; }
			;;
esac
if [ $# -eq 0 -a ${#allFiles[@]} -eq 0 ]; then
    # Alert when no file passed; git checkout then prints the unhelpful "error: you need to resolve your current index first"
    printUsage "$0"
    exit 2
fi

exec git checkout --conflict=diff3 "$@" "${allFiles[@]}"
