#!/bin/bash

if [ $# -eq 0 ]; then
    echo >&2 "ERROR: Must pass remote and branch name"
    exit 2
fi
remote=$1; shift

if [ $# -eq 0 ]; then
    echo >&2 "ERROR: Must pass branch name"
    exit 2
fi
branch=${!#}
exec git checkout "${@:1:$(($#-1))}" --track "${remote}/${branch:?}"
