#!/bin/sh

if [ "$(uname -o 2>/dev/null)" = "Cygwin" ]; then
    mkdir -p /usr/etc || exit $?
    touch /usr/etc/gitconfig || exit $?

    # Stop recording the executable file mode.
    # This can be necessary when using both MSysGit and Cygwin's Git, and
    # "git diff" shows this output for every file:
    #   old mode 100755
    #   new mode 100644
    git config --system core.filemode false

    # Avoid SSL certificate errors when using https:// URLs due to the fact
    # that the up-to-date browser certificates may not be available to Git.
    git config --system http.sslVerify false


    # Show all applied configuration changes.
    git config --system --list
fi
