#!/bin/bash

remote="${1:?}"; shift
url=$(git-remoteurl "$remote") || exit $?

if [ "$1" = '--' ]; then
    shift
elif rev="$(git-commitid --no-error "$1")"; then
    shift
    [ "$1" = '--' ] && shift
fi
[ "$rev" ] || rev=HEAD

for filespec
do
    hash="$(git lh --max-count 1 "$rev" -- "$filespec")"
    git-lll --prefix "${url%/}/blob/${hash}/" --transform 'urlencode --filespec --newlines -' --no-classify "$filespec"
done
