#!/bin/bash

if git checkout "$@"; then
    gitDir=$(git rev-parse --git-dir 2>/dev/null) || exit $?
    baseBranchStore="${gitDir}/baseBranch"

    baseBranch="$(git-nbr 2>/dev/null)"
    newBranch="$(git-brname --raw 2>/dev/null)"
    if [ "$newBranch" ] && [ "$newBranch" != "$baseBranch" ]; then
	typeset what=Set; [ "$baseBranch" ] && what=Changed
	printf '%s\n' "$newBranch" > "$baseBranchStore" &&
	    printf '%s base branch to %s.\n' "$what" "$newBranch"
    fi
fi
