#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Interactively select (from modified files or passed list of files) files (or
directly pass N, M, ... selections) to diff by number.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[N [M ...]] [--] [FILE ...] [-?|-h|--help]'
}

diffCommand="${GIT_DIFFSELECTED_DIFFCOMMAND:-diff}"
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --cached)		diffCommand="$diffCommand $1"; shift; export GIT_SELECTED_COMMAND_DEFAULT_FILES='git diff --name-only --cached --';;
esac

exec git-selected-command "$diffCommand" "$@"	# Note: Need to quote diffCommand because git-selected-command expects it as one argument (and expands it itself).
