#!/bin/bash

[ $# -gt 0 ] || exit 2

prevCommitId=
for rev
do
    commitId=$(git-commitid "$rev") || exit $?
    if [ "$prevCommitId" -a "$prevCommitId" != "$commitId" ]; then
	exit 1
    fi
    prevCommitId=$commitId
done
