#!/bin/sh

# Source:
#   https://stackoverflow.com/questions/30208928/can-git-pull-automatically-stash-and-pop-pending-changes
#   https://github.com/aanand/git-up

# Git 2.6 and later.
exec git -c rebase.autoStash=true pull --rebase=preserve "$@"

# Git 2.9 and later.
#exec git pull --rebase=preserve --autostash "$@"
