#!/bin/bash

gitDir=$(git rev-parse --git-dir 2>/dev/null) || exit $?
if ! [ "$1" = '--absolute' -o "$1" = '-a' ] && type -t reldate >/dev/null; then
    exec reldate "${gitDir}/FETCH_HEAD"
else
    exec stat -c %y "${gitDir}/FETCH_HEAD"
fi
