#!/bin/bash

if git-dirty; then
    echo >&2 "ERROR: working copy is still dirty; please clean up first."
    git status
    exit 1
fi

if [ "$GIT_CHECKOUTPREVIOUS_COMMIT" ]; then
    rev="$GIT_CHECKOUTPREVIOUS_COMMIT"
else
    if [ "$1" = '--' ]; then
	shift
    elif rev="$(git-commitid --no-error "$1")"; then
	shift
	[ "$1" = '--' ] && shift
    fi
    [ "$rev" ] || rev=HEAD
fi

git checkout "${rev}^" -- "${@:-.}" && git unstage >/dev/null && git st
