#!/bin/bash

ensureValidRef()
{
    if ! git show-ref "$1" > /dev/null; then
	echo >&2 "bad ref: $1"
	exit 1
    fi
}

if [ $# -eq 2 ]; then
    localBranch=$1
    remoteBranch=$2
elif [ $# -eq 1 ]; then
    localBranch=$(git-brname)
    remoteBranch=$1
else
    localBranch=$(git-brname)
    remoteBranch=$(git tracks) || exit $?
fi

ensureValidRef "$localBranch"
ensureValidRef "$remoteBranch"

set -o pipefail
(
    echo "incoming ${remoteBranch} -> ${localBranch}:"
    git-onelinelog --no-pager "$localBranch..$remoteBranch"

    echo
    echo "outgoing ${localBranch} -> ${remoteBranch}:"
    git-onelinelog --no-pager "$remoteBranch..$localBranch"
) | "${PAGER:-less}" --RAW-CONTROL-CHARS
