#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
    List local branches ordered by date of most recent commit.
    Pass -r to list remote-tracking branches.
    Pass -a to list both.
    The branches can be optionally filtered by <branch-glob>.
Usage: "$(basename "$1")" [-r|-a] [<branch-glob>] [-?|-h|--help]
HELPTEXT
}

what="refs/heads/$1"
case $1 in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    -a)	what="refs/heads/$2 refs/remotes/$2";;
    -r) what="refs/remotes/$2";;
esac
git for-each-ref --sort=committerdate --format='(%(authorname), %(committerdate:relative))%09%(refname:short)' $what
