#!/bin/bash

typeset -a editArgs=()
read -p "Do you want to check / edit every extracted version message? (y/n) " choice
[ "$choice" = 'y' ] && editArgs=(--edit-plugin-message)

exec git-writebackup-import "${editArgs[@]}" --commit-message-plugin ingo-extract-version-message "$@"
