#!/bin/sh

if [ $# -eq 0 ]; then
    echo >&2 'Need <commit> to reset the working copy to!'
    exit 2
elif [ "$(git diff --shortstat 2>/dev/null | tail -n 1)" ]; then
    echo "Unstaged changes:"
    git status --porcelain | grep -v '^??'
    exit 1
fi

exec git reset --hard "$@"
