#!/bin/bash

if git-dirty; then
    echo >&2 "ERROR: working copy is still dirty; please clean up first."
    git status
    exit 1
fi

commit="${1:?}"; shift
git checkout "${commit}^" -- "${@:-.}" && git unstage >/dev/null && git st
