#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Log only those commits where log messages match the specified text or /regexp/.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[<log-options>] [<revision range>] [[--] <path>...] text|/regexp/ [-?|-h|--help]'
}

typeset -a logArgs=()
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -eq 0 ]; then
    printUsage "$0"
    exit 2
fi

# The last argument is the text or /regexp/.
lastArg="${!#}"
searchString=$(printf '%s' "$lastArg" | sed -ne 's/^\([^a-zA-Z0-9]\)\(.*\)\1$/\2/p')
if [ "$searchString" ]; then
    logArgs+=(--grep "$searchString")
else
    logArgs+=(--grep "$lastArg" --fixed-strings)
fi

exec git-wrapper "${GIT_LOGG_COMMAND:-log}" "${logArgs[@]}" "${@:1:$(($#-1))}"
