#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Show all changes from today in a single big diff (not individual commits) unless
a different date or commit range is given.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--since=<date>] [<path>] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

typeset arg=
typeset allargs=()
typeset rangeArg='@{yesterday}..HEAD'
for arg
do
    case "$arg" in
	--since=*)  rangeArg="@{${1#--since=}}..HEAD";;
	*..*)	    rangeArg=$1;;
	*)	    allargs+=("$arg");;
    esac
done

exec git diff $rangeArg "${allargs[@]}"
