#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Diff with predecessor, either current HEAD or passed revision,
optionally limited to files in <path>. 
Like the textual diff output of "git show", without the log info. 
Usage: "$(basename "$1")" [REVISION] [<common diff options>] [--] [<path>...] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

revision='HEAD'
if [ $# -gt 0 -a "${1:0:1}" != '-' -a ! -e "$1" ]; then
    # Take the first argument as a commit specification unless it looks like a
    # diff argument or is an existing file. 
    revision=$1
    shift
fi

exec git diff "${revision}^" "$revision" "$@"
