#!/bin/bash

shopt -qs extglob

printUsage()
{
    cat <<HELPTEXT
    Merge all / the N local branches (except for the current branch and master)
    ordered by date of first commit.
Usage: "$(basename "$1")" [N] [--no-commit] [--squash] [-s <strategy>] [-m <msg>]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

branches=$(git-brc | awk '{ print $NF }') || exit $?
git-mergelocalbr --branches "$branches" "$@"
