#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Show all commits from today unless a different date or commit range is given.
Usage: "$(basename "$1")" [--since=<date>] [<path>] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

[ -t 1 ] && colorArg="--color" || colorArg="--no-color"

sinceArg='--since="1 day ago"'
for argument
do
    case "$argument" in
	--since=*)  sinceArg=;;
	*..*)	    sinceArg=;;
    esac
done

readonly gitUserName=$(git config --get user.name)
eval 'git-log $colorArg --pretty=medium' $sinceArg '"$@"' | sed -e "
/Author: ${gitUserName}/d"'
/^Date:/d
/^Merge:/d' | less --RAW-CONTROL-CHARS
