#!/bin/bash

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }

"$@"
status=$?

# XXX: My git-bisect is not accessible through PATH when executed by "git
# bisect"; therefore need to invoke it with the full filespec.
case "$status" in
    0)	    "${scriptDir}/git-bisect" --report-only "${termOld:-good}";;
    125)    "${scriptDir}/git-bisect" --report-only skip;;
    *)	    "${scriptDir}/git-bisect" --report-only "${termNew:-bad}";;
esac

exit $status
