#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Create (and track) local branches for all branches in origin (matching PATTERN).
Usage: "$(basename "$1")" [PATTERN] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

case "$1" in
    ^*)	pattern=${1#^};;
    *)	pattern=".*$1";;
esac
exec git-cobr "^ *origin/$pattern"
