#!/bin/bash

gitDir=$(git rev-parse --git-dir 2>/dev/null) || exit $?
baseBranchStore="${gitDir}/baseBranch"
baseBranch=; [ -r "$baseBranchStore" ] && < "$baseBranchStore" IFS=$'\n' read -r baseBranch

if [ "$baseBranch" ]; then
    printf '%s\n' "$baseBranch"
else
    echo >&2 'No base branch defined; use git nco <branch> first.'
    exit 1
fi
