#!/bin/bash

if git-dirty; then
    echo >&2 "ERROR: working copy is still dirty; please clean up first."
    git status
    exit 1
fi

if [ "$GIT_CHECKOUTPREVIOUS_COMMIT" ]; then
    commit="$GIT_CHECKOUTPREVIOUS_COMMIT"
else
    commit="${1:?}"; shift
fi

git checkout "${commit}^" -- "${@:-.}" && git unstage >/dev/null && git st
