#!/bin/bash
set -o pipefail

# Highlight diff output if available.
hasColorDiff=
type -t colordiff >/dev/null && [ -t 1 ] && hasColorDiff=t

typeset -a allargs=()
while [ $# -gt 0 ]
do
    case "$1" in
	--no-color|--color=never)
	    shift
	    hasColorDiff=
	    ;;
	--color|--color=always)
	    shift
	    hasColorDiff=t
	    ;;
	*)
	    allargs+=("$1")
	    shift
	    ;;
    esac
done

if [ "$hasColorDiff" ]; then
    git difftool -y --extcmd "diff -c" "${allargs[@]}" | colordiff | "${PAGER:-less}" --quit-on-intr --RAW-CONTROL-CHARS
else
    git difftool -y --extcmd "diff -c" "${allargs[@]}" | "${PAGER:-less}" --quit-on-intr --RAW-CONTROL-CHARS
fi
