#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Test whether the working copy has either:
- uncommitted changes
- where not all commits (on the current branch) have already been pushed to
  origin (or origin doesn't even exist yet)
- where the last commit had "WIP:" in the message summary
- not on the master branch
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
    --quiet|-q)		shift; exec 1>/dev/null;;
esac


if git dirty; then git st; exit 0; fi

if ! git existsremote; then echo "Local-only repository; no remotes defined yet."; exit 0; fi

if git existsremote origin && git remotebr origin >/dev/null 2>&1 && git ooutlgn; then exit 0; fi

if git l --max-count=1 | grep '\(^\| \)WIP: '; then exit 0; fi

if branchName="$(git brname)"; [ "$branchName" != 'master' ]; then printf 'On branch %s\n' "$branchName"; exit 0; fi

exit 1
