#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Execute "git COMMAND" on each passed WORKING-COPY.
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[--no-pager] WORKING-COPY [...] -- [COMMAND ...] [-?|-h|--help]'
}

typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS)
typeset -a wcs=()
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--no-pager)	shift; pager=();;
	--)		shift; break;;
	*)		wcs+=("$1")
			shift
			;;
    esac
done
[ ${#wcs[@]} -eq 0 ] && { printUsage "$0"; exit 2; }
[ $# -eq 0 ] && set -- noop

# Because of the piping into the pager, we need to explicitly enable color.
# Don't do this if the user explicitly turned it off, though.
typeset -a colorArg=(--color=always)
if [ ! "$pager" -o ! -t 1 ] || contains '--no-color' "$@" || contains '--color=never' "$@"; then
    colorArg=()
fi



filterEmpty()
{
    awk '
	/^\[01m\S+\[0m:$/ {
	    suspect = $0
	    while (1) {
		lookahead = ""
		while (lookahead ~ /^\n*$/) {
		    if (getline lookahead != 1) {
			next
		    }
		}
		if (lookahead ~ /\n*\[01m\S+\[0m:$/) {
		    gsub(/^\n*/, "", lookahead)
		    suspect = lookahead
		} else {
		    print suspect
		    print lookahead
		    fflush()
		    next
		}
	    }
	}
	{
	    print
	    fflush()
	}
    ' | sed -e '${ /^$/d }'
}

separator=
exitStatus=0
for dir in "${wcs[@]}"
do
    printf "${separator}[01m%s[0m:\n" "${dir##*/}"
    separator='\n'
    cd "$dir" && git "$@" "${colorArg[@]}" || exitStatus=$?
done 2>&1 | eval "filterEmpty ${pager:+|}" '"${pager[@]}"'
exit $exitStatus
