#!/bin/bash
# Written by Corey Haines
# Scriptified by Gary Bernhardt
set -o pipefail

printUsage()
{
    cat <<HELPTEXT
Show sorted number of changes per file; arguments as to git log, e.g. --since="1 month ago" SUBDIR
HELPTEXT
    printf 'Usage: %q %s\n' "$(basename "$1")" '[<revision range>] [[--] <path>...] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
typeset -a pager=("${PAGER:-less}" --RAW-CONTROL-CHARS); [ -t 1 ] || pager=()
git log -M -C --name-only --format='format:' "$@" | \
    sort | grep -v '^$' | uniq -c | \
    eval 'sort -nr' "${pager:+|}" '"${pager[@]}"'
