#!/bin/bash
# Source:
#   http://codingkilledthecat.wordpress.com/2012/04/27/git-stash-pop-considered-harmful/

contains()
{
    needle=$1
    shift
    for elem
    do
	[ "$needle" = "$elem" ] && return 0
    done
    return 1
}

printUsage()
{
    cat <<HELPTEXT
Stash the changes in a dirty working directory in a new branch.
HELPTEXT
    printf 'Usage: %q  %s\n' "$(basename "$1")" '<branch> [-m <msg>] [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -eq 0 ]; then
    echo >&2 'Need new <branch> to stash to!'
    exit 2
fi

typeset -a defaultMessageArgs=()
if ! contains -m "$@" && ! contains --message "$@"; then
    printf -v defaultMessage 'WIP on %s: %s' "$(git-brname)" "$(git log --pretty='tformat:%h %s' -1)"
    defaultMessageArgs=(--message "$defaultMessage")
fi

newBranch=$1; shift
git checkout -b "$newBranch" && git-commit --all "${defaultMessageArgs[@]}" "$@" && git checkout '@{-1}'
