#!/bin/bash

prefix=
typeset -a transformer=()
while [ $# -ne 0 ]
do
    case "$1" in
	--prefix)	shift; prefix="$1"; shift;;
	--transform)	shift; eval "transformer=($1)"; shift;;
	*)		break;;
    esac
done

relDir="$(git rev-parse --show-prefix)" || exit $?
literalRelDir="${prefix}$relDir"
literalRelDir="${literalRelDir//\\/\\\\}"
literalRelDir="${literalRelDir//&/\\&}"

eval 'git-ls "$@"' "${transformer:+|}" '"${transformer[@]}"'| sed -e "s#^#${literalRelDir//#/\\#}#"
