#!/bin/bash

if [ $# -eq 0 -o "$1" = '-' ]; then
    typeset -a candidateArgs=()
elif [ $# -ge 2 ] && ! [[ "$1" =~ @ ]] && [[ "$2" =~ ^[^\ ]+@[^\ ]+$ ]]; then
    typeset -a candidateArgs=("$1" "$2")
    shift
else
    typeset -a candidateArgs=("$1")
fi; shift
author=$(git-whois --accept-unknown --select "${candidateArgs[@]}") || exit $!

if [ ! "$author" ]; then
    echo >&2 "ERROR: No author!"
    exit 1
fi

exec git-commit --author "$author" "$@"
