#!/bin/bash

remote=${1:?}; shift

if [ $# -eq 0 ]; then
    branch=$(git-brname) || exit $?
    set -- "$branch"
fi

status=0
for branch
do
    trackedBranch=$(git-tracks "$branch" 2>/dev/null)
    if [ "${trackedBranch%%/*}" = "$remote" ]; then
	remoteCandidate=$trackedBranch
    else
	remoteCandidate="${remote}/$branch"
    fi

    if git-existsbr "$remoteCandidate"; then
	printf '%s\n' "$remoteCandidate"
    else
	if git-existsremote "$remote"; then
	    printf >&2 '%s does not have a branch for %s.\n' "$remote" "$branch"
	else
	    printf >&2 '%s does not exist as a remote.\n' "$remote"
	fi
	status=1
    fi
done
exit $status
