#!/bin/bash

if [ $# -eq 0 ]; then
    echo >&2 'ERROR: No <branch> passed.'
    exit 2
fi

# First check whether any valid ref is passed.
git rev-parse --verify --quiet "$@" >/dev/null || exit 1

# Then verify that a branch with that name exists (and it isn't a tag or raw
# commit).
for branch
do
    [ "$(git branch --list --all "$branch")" ] || exit 1
done
