#!/bin/bash
shopt -qs extglob

TMPDIR="$(mktemp --directory --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || { dirspec="${TEMP:-/tmp}/$(basename -- "$0").$$$RANDOM"; mkdir -p -- "$dirspec" && printf %s "$dirspec"; })" || exit $?
[ "$DEBUG" ] || trap 'rm -rf "$TMPDIR" 2>/dev/null' EXIT

typeset -a showArgs=()
while [ $# -ne 0 ]
do
    case "$1" in
	-[UBMClSGO])	showArgs+=("$1" "$2"); shift; shift;;
	-[UBMClSGO]?*)	showArgs+=("$1"); shift; shift;;
	--@(pretty|format|encoding|unified|diff-algorithm|word-diff-regex|ws-error-highlight|diff-filter|src-prefix|dst-prefix))	showArgs+=("$1" "$2"); shift; shift;;
	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
	--)		showArgs+=("$1"); shift; break;;
	--*)	showArgs+=("$1"); shift;;
	-*)	showArgs+=("$1"); shift;;
	*)		break;;
    esac
done

typeset -a outputs=()
status=0
for object
do
    tempOutput="${TMPDIR}/$object"
    git show "${showArgs[@]}" "$object" > "$tempOutput" || status=$?
    [ -s  "$tempOutput" ] && outputs+=("$tempOutput")
done

if ! isColorOffArgument "${showArgs[@]}"; then
    pipethrough --piped -- colordiff --color=yes -- "${outputs[@]}" 2>/dev/null
fi

[ "$PAGER" = smartless ] && PAGER=less	# smartless does not page small outputs that fit the terminal, but we explicitly want to page through each date range separately.
"${PAGER:-less}" --RAW-CONTROL-CHARS "${outputs[@]}" || status=$?
exit $status
