#!/bin/bash

gitDir=$(git rev-parse --git-dir 2>/dev/null) || exit $?

if [ -f "${gitDir}/MERGE_HEAD" ]; then
    git reset --merge
elif [ -f "${gitDir}/CHERRY_PICK_HEAD" ]; then
    git cherry-pick --abort
else
    echo >&2 "ERROR: It appears that you're neither merging nor cherry-picking."
    exit 1
fi
