#!/bin/bash
set -o pipefail

if [ $# -eq 0 ]; then
    echo >&2 'ERROR: No GIT-COMMAND passed.'
    exit 2
fi
typeset -a gitCommand=()
while [ $# -ne 0 ]
do
    case "$1" in
	-c) gitCommand+=("$1" "$2"); shift; shift;;
	*)  gitCommand+=("$1"); shift; break;;
    esac
done

printUsage()
{
    cat <<HELPTEXT
Show first tag [that matches GREP-ARGS] that the passed <commit> is based on.
HELPTEXT
    printf 'Usage: %q %s %s\n' "$(basename "$1")" "${gitCommand[-1]}" '[GREP-ARGS] <commit> [-?|-h|--help]'
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac
if [ $# -eq 0 ]; then
    printUsage "$0" 2>&1
    echo >&2 'ERROR: Must pass <commit>'
    exit 2
fi
revision="${!#}"
typeset -a grepArgs=("${@:1:$(($#-1))}")

eval 'git "${gitCommand[@]}" --contains "$revision" | ' ${grepArgs:+grep} '"${grepArgs[@]}"' ${grepArgs:+|} 'head -n 1' 2>/dev/null || \
    git name-rev --name-only "$revision"
