#!/bin/sh

printUsage()
{
    cat <<HELPTEXT
Remove unversioned files. 
With -r also any unversioned directory trees. 
With -x also files from the ignore list. 
Usage: "$(basename "$1")" [-r] [-x] [<path>] [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

recursiveFlag=
if [ "$1" = "-r" ]; then
    recursiveFlag='-d'
    shift
fi

exec git clean $recursiveFlag "$@"
