#!/bin/bash

me="$(git config --get user.name)" || exit $?

optionName='--author='
if [ "$1" = '--no-option-name' ]; then
    shift; optionName=
fi

typeset -a gitCommand=();
case "$1" in
    [^-]*-command)  gitCommand+=("$1"); shift
		    while [ $# -ne 0 ]
		    do
			case "$1" in
			    -*)		gitCommand+=("$1"); shift;;
			    *)		gitCommand+=("$1"); shift; break;;
			esac
		    done
		    ;;
    *)		    gitCommand+=("$1"); shift;;
esac

exec git-wrapper "${gitCommand[@]}" "${optionName}${me}" "$@"
