#!/bin/bash

formatPrefix=
formatSuffix=
maxDepth=1
typeset -a gitLogArgs=()
while [ $# -ne 0 ]
do
    case "$1" in
	--)		shift; break;;
	--long|-l)	shift; formatPrefix='%h %<(12,trunc)%aN %<(22)%ad '; formatSuffix=;;
	--directory|-d)	shift; maxDepth=0;;
	--date)			gitLogArgs+=("$1" "$2"); shift; shift;;
	--relative-date)	gitLogArgs+=("$1"); shift;;
	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
	*)		break;;
    esac
done

listFiles()
{
    find "${@#${PWD}/}" -maxdepth "$maxDepth" -print | sort
}

IFS=$'\n'
for filespec in $(listFiles "$@")
do
    filespec=${filespec#./}
    if [ -d "$filespec" ]; then
	# Print directory (name) if it contains any tracked files.
	if git ls-files --error-unmatch -- "$filespec" >/dev/null 2>&1; then
	    printf '%s/\n' "${filespec%/}"
	fi
    else
	git ls-files --error-unmatch -- "$filespec" 2>/dev/null
    fi
done
