#!/bin/bash

printUsage()
{
    cat <<HELPTEXT
Synchronize the local repository with the major remotes:
- Fetch upstream changes
- Pull origin changes
- Create (and track) local branches for all branches in origin.
- Remove old local branches that do not exist in origin any more.
Usage: "$(basename "$1")" [-?|-h|--help]
HELPTEXT
}
case "$1" in
    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
esac

status=0

if git remote | grep -q -e "^upstream$"; then
    git ufetch || status=$?
else
    echo "No upstream configured."
fi
echo "Getting updates from origin:"
git opull || status=$?
git-ocobr -q || status=$?
git-oprune || status=$?

exit $status
