#!/bin/sh
# Use socat to proxy git through an HTTP CONNECT firewall.
# Useful if you are trying to clone git:// from inside a company.
# Requires that the proxy allows CONNECT to port 9418.
#
# Make this file executable and save it as gitproxy somewhere in your PATH
# (e.g., ~/bin) and then enable it via: 
#   export GIT_PROXY_COMMAND="gitproxy"
#
# You can also make this permanent via: 
#   git config --global core.gitproxy gitproxy
#
# More details at http://tinyurl.com/8xvpny

# Configuration. Common proxy ports are 3128, 8123, 8000.
_proxy=web-proxy.atl.hp.com
_proxyport=8088

exec socat STDIO PROXY:$_proxy:$1:$2,proxyport=$_proxyport
