#!/bin/bash

if [ $# -eq 0 -o "${1:0:1}" = '-' ]; then
    # XXX: hub pr (in version 2.10.0) does not default to "list" (like hub
    # issue). DWIM and add this.
    set -- list "$@"
fi
exec hub pr "$@"
