#!/bin/bash
set -o pipefail
readonly ANSI_ESCAPE_PATTERN='\(\[[0-9;]*[mK]\)'

sedLiteral()
{
    printf %s "${1:?}" | sed -e 's/[][\$*.^/]/\\&/g'
}
setAnsiFilter()
{
    filter=(sed -e "/\t\\(${ANSI_ESCAPE_PATTERN}\\?[^\t]*, \\|${ANSI_ESCAPE_PATTERN}\\)$(sedLiteral "${1:?}")\\(, [^\t]*${ANSI_ESCAPE_PATTERN}\\?\$\\|${ANSI_ESCAPE_PATTERN}\\?\$\\)/!d")
}
setPlainFilter()
{
    filter=(sed -e "s/|\\(.*, \\)\\?$(sedLiteral "${1:?}")\\(, .*\\)\\?$//" -e t -e d)
}

typeset -a filter=()
formatAddition=
typeset -a args=()
typeset -a colorArg=()
typeset -a formatArgs=()
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)		shift; printUsage "$0"; exit 0;;
	--reviewer)		shift; setAnsiFilter "$1"; shift;;
	--reviewer=*)		setAnsiFilter "${1#--reviewer=}"; shift;;
	--creator)		shift; formatAddition="|%au"; setPlainFilter "$1"; shift;;
	--creator=*)		formatAddition="|%au"; setPlainFilter "${1#--creator=}"; shift;;
	--assignee)		shift; formatAddition="|%as"; setPlainFilter "$1"; shift;;
	--assignee=*)		formatAddition="|%as"; setPlainFilter "${1#--assignee=}"; shift;;
	--no-color|--color=*)	colorArg=("$1"); shift;;
	--color)		colorArg=("$1" "$2"); shift; shift;;
	--format|-f)		formatArgs+=("$1" "${2%'%n'}	%rs%n"); shift; shift;;
	--)			args+=("$1"); shift; break;;
	*)			args+=("$1"); shift;;
    esac
done

[ ${#formatArgs[@]} -eq 0 ] && formatArgs=(--format '%pC%>(8)%i%Creset  %t%  l	%Ccyan%rs%Creset%n')
[ -n "$formatAddition" ] && formatArgs[1]="${formatArgs[1]%'%n'}${formatAddition}%n"
isNeedColorArgumentWhenPiping "${colorArg[@]}" && colorArg=(--color=always) || colorArg=()

eval 'command hub pr list "${colorArg[@]}" "${formatArgs[@]}" "${args[@]}" "$@"' "${filter:+|}" '"${filter[@]}"' | \
    grep -e "	${ANSI_ESCAPE_PATTERN}\\?[^	]\\+${ANSI_ESCAPE_PATTERN}\\?\$"
