#!/bin/bash
set -o pipefail

if [ $# -eq 0 -o "${1:0:1}" = '-' ]; then
    case "$1" in
	--assignee=*|--creator=*|--mentioned=*)
	    # XXX: hub pr (in version 2.10.0) cannot filter yet, but we can
	    # misuse hub issue for it (with filtering).
	    typeset -a args=()
	    typeset -a colorArg=()
	    while [ $# -ne 0 ]
	    do
		case "$1" in
		    --help|-h|-\?)		shift; printUsage "$0"; exit 0;;
		    --no-color|--color=*)	colorArg=("$1"); shift;;
		    --color)			colorArg=("$1" "$2"); shift; shift;;
		    --format|-f)		echo >&2 "ERROR: Cannot use -f|--format here."; exit 2;;
		    --)				args+=("$1"); shift; break;;
		    *)				args+=("$1"); shift;;
		esac
	    done
	    isNeedColorArgumentWhenPiping "${colorArg[@]}" && colorArg=(--color=always) || colorArg=()

	    hub issue --include-pulls --format '%U	%sC%>(8)%i%Creset  %t%  l%n' "${colorArg[@]}" "${args[@]}" "$@" | sed -e 's#^[^\t]\+/pull/[^\t]\+\t\(.*\)$#\1#' -e t -e 'd'
	    exit $?
	    ;;
    esac

    # XXX: hub pr (in version 2.10.0) does not default to "list" (like hub
    # issue). DWIM and add this.
    set -- list "$@"
fi
exec hub pr "$@"
