#!/bin/bash
set -o pipefail
readonly ANSI_ESCAPE_PATTERN='\(\[[0-9;]*[mK]\)'

typeset -a args=()
typeset -a colorArg=()
hasFormat=
while [ $# -ne 0 ]
do
    case "$1" in
	--help|-h|-\?)		shift; printUsage "$0"; exit 0;;
	--no-color|--color=*)	colorArg=("$1"); shift;;
	--color)		colorArg=("$1" "$2"); shift; shift;;
	--format|-f)		args+=("$1" "${2%'%n'} -> %rs%n"); hasFormat=t; shift; shift;;
	--)			args+=("$1"); shift; break;;
	*)			args+=("$1"); shift;;
    esac
done

typeset -a formatArgs=(); [ "$hasFormat" ] || formatArgs=(--format '%pC%>(8)%i%Creset  %t%  l -> %Ccyan%rs%Creset%n')
isNeedColorArgumentWhenPiping "${colorArg[@]}" && colorArg=(--color=always) || colorArg=()

command hub pr list "${colorArg[@]}" "${formatArgs[@]}" "${args[@]}" "$@" | \
    grep -e " -> ${ANSI_ESCAPE_PATTERN}\\?[^->]\\+${ANSI_ESCAPE_PATTERN}\\?\$"
