#!/bin/sh

# Need to push to remote first so that GitHub recognizes that the branch has
# been merged. If the branch is first deleted, GitHub marks a corresponding pull
# request as "closed".
exec git reintegratetolb --push "$@"
